### ISSUE TITLE
交点サークル，ブロックサークルの座標のズレを修正する．

### ISSUE THREAD

**Issue by Tatsumi0000** [KatLab-MiyazakiUniv/CameraSystem#61]
### なぜやるか
- 台形補正時のズレにより画像が100%正面から向いたものではない．
- そのためプルリク #60 では，交点サークル，ブロックサークルの座標が微妙にずれている．
- そのため，計算して出したサークルの座標をマウスでう動かして修正したい．

### 方法
- [これ](https://github.com/arccoder/opencvdragrect)を参考に作る．
- Tkinterを使って頑張る．
- **他のやり方も募集中．**

### 完了条件
- 画像認識できるようになる

**Comment by korosuke613** [comment]
https://youtu.be/6-ViiADoSew
